# Copyright (C) 2026 Kevin Monaghan. All rights reserved.
#
# This file is proprietary and confidential.
# Unauthorized copying, use, modification, distribution, or disclosure of this file,
# via any medium, is strictly prohibited except under a written agreement with the
# copyright owner.

[licenses]
version = 2
confidence-threshold = 0.8
private = { ignore = true }
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[advisories]
version = 2
yanked = "deny"
ignore = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
